chore: applied consitent formatting to global project files but not the Helm charts

diff --git a/.github/template/bump-version/action.yml b/.github/template/bump-version/action.yml
--- a/.github/template/bump-version/action.yml
+++ b/.github/template/bump-version/action.yml
@@ -3,20 +3,20 @@ description: Bump chart versions
 
 inputs:
   changes:
-    description: | 
+    description: |
       A string of charts and their required update, e.g. "icm-as:minor icm-web:patch". 
       Dependent charts don't have to be specified and will be bumped automatically.
     required: true
 
 runs:
-  using: "composite"
+  using: 'composite'
   steps:
-  - name: Bump Version
-    shell: bash
-    run: |
-      if [[ -z "${{inputs.changes}}" ]]; then
-        echo "Missing parameter inputs.changes" 1>&2
-        exit 1
-      fi
-      pip install --no-cache-dir bump-my-version==0.12.0
-      python ./.github/callBump2version.py ${{inputs.changes}}
+    - name: Bump Version
+      shell: bash
+      run: |
+        if [[ -z "${{inputs.changes}}" ]]; then
+          echo "Missing parameter inputs.changes" 1>&2
+          exit 1
+        fi
+        pip install --no-cache-dir bump-my-version==0.12.0
+        python ./.github/callBump2version.py ${{inputs.changes}}
